name: Test with Jest and Cypress
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:3000'

      # test with jest
      - run: yarn run test
